refactor: typescript implementation
MapColonies/planet-dumper pull request #18
Opened 2022-01-26 17:59 UTC by melancholiai

2022-01-30 12:26 UTC, CptSchnitz requested changes

2022-01-30 12:26 UTC, CptSchnitz commented on .nvmrc
> +v12
v14

2022-01-30 12:26 UTC, CptSchnitz commented on Dockerfile
>  FROM ubuntu:20.04 AS builder
better naming

2022-01-30 12:26 UTC, CptSchnitz commented on package.json
> +    "zx": "^4.2.0"
?

2022-01-30 12:26 UTC, CptSchnitz commented on src/s3client/s3Client.ts
> +/* eslint-disable @typescript-eslint/naming-convention */ // s3-client object commands arguments
?

2022-02-13 12:50 UTC, melancholiai commented on .nvmrc
> +v12
done.

2022-02-13 12:50 UTC, melancholiai commented on Dockerfile
>  FROM ubuntu:20.04 AS builder
done.

2022-02-13 12:50 UTC, melancholiai commented on package.json
> +    "zx": "^4.2.0"
done.

2022-02-13 12:51 UTC, melancholiai commented on src/s3client/s3Client.ts
> +/* eslint-disable @typescript-eslint/naming-convention */ // s3-client object commands arguments
done.

2022-02-28 11:43 UTC, merged