feat: planet dumper as typescript cli
MapColonies/planet-dumper pull request #20
Opened 2022-02-14 14:56 UTC by melancholiai

docs are missing

2022-02-21 08:06 UTC, CptSchnitz requested changes

2022-02-21 08:06 UTC, CptSchnitz commented on src/commands/create/create.ts
> +        demandOption: true,
use the `.choices` option to limit the acl.
also put a default value instead of demanding the option.

2022-02-21 08:06 UTC, CptSchnitz commented on src/commands/create/create.ts
> +      }
this is business logic and should be in the manager and not the handler. same as with http controllers.

2022-02-21 08:06 UTC, CptSchnitz commented on src/commands/create/createManager.ts
> +  public async createNgDump(pgDumpFilePath: string, ngDumpName: string): Promise<string> {
i know it has been like this, but lets change Ng to OSM for better clarity. "new generation" dump is not very informative.

2022-02-21 08:06 UTC, CptSchnitz commented on src/commands/create/createManager.ts
> +  public async uploadDumpToS3(filePath: string, bucketName: string, key: string, acl: string): Promise<void> {
its more of a upload file than dump.

2022-02-21 08:06 UTC, CptSchnitz commented on src/commands/create/createManager.ts
> +  public async uploadToDumpServer(dumpServerConfig: DumpServerConfig, dumpMetadata: DumpMetadata): Promise<void> {
you dont upload anything to dump server. you `register` or something like that.

2022-02-21 10:08 UTC, melancholiai commented on src/commands/create/create.ts
> +      }
as discussed, this logic will remain in the handler

2022-02-21 10:08 UTC, melancholiai commented on src/commands/create/createManager.ts
> +  public async createNgDump(pgDumpFilePath: string, ngDumpName: string): Promise<string> {
done.

2022-02-21 10:08 UTC, melancholiai commented on src/commands/create/createManager.ts
> +  public async uploadToDumpServer(dumpServerConfig: DumpServerConfig, dumpMetadata: DumpMetadata): Promise<void> {
done.

2022-02-21 10:09 UTC, melancholiai commented on src/commands/create/create.ts
> +        demandOption: true,
done.

2022-02-28 12:00 UTC, CptSchnitz approved these changes

2022-02-28 12:01 UTC, merged